[phases.setup]
nixPkgs = ['gcc', 'rust-bin.stable.latest.default', 'openssl']
aptPkgs = ['libc=2.3.4']

[phases.install]
cmds = ['cargo prisma generate']

[phases.build]
cmds = ['cargo build --release --package oxy-login']
dependsOn = ['install']

[start]
cmd = 'cargo l'