[setup]
nixPkgs = ['gcc', 'rust-bin.stable.latest.default', 'binutils']

[install]
cmds = ['cargo prisma generate']

[build]
cmds = ['cargo build --release --package oxy-login']

[start]
cmd = 'cargo l'