[phases.setup]
nixPkgs = ['gcc', 'rust-bin.stable.latest.default', 'binutils']

[phases.install]
cmds = ['cargo prisma generate']

[phases.build]
cmds = ['cargo build --release --package oxy-login']

[start]
cmd = 'cargo l'