[package]
name = "cygnus"
version = "0.1.0"
edition = "2021"

[dependencies]
oxy-core = { path = "../oxy-core" }

anyhow = "1.0.65"
bytes = "1.2.1"
log = "0.4.17"
rand = "0.8.5"
simple_logger = "2.3.0"
tokio = { version = "1.21.2", features = ["full"] }
