[package]
name = "cygnus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.61"
bytes = "1.3.0"
log = "0.4.17"
oxy-core = { path = "../oxy-core" }
rand = "0.8.5"
simple_logger = "4.0.0"
tokio = { version = "1.24.1", features = ["full"] }
