enable_pin = false
enable_pic = true

[[worlds]]
id = 0
name = "Scania"
channels = 10
flag = 0
event_message = "Scania!"
recommended_message = "Welcome to Scania!"
exp_rate = 10
meso_rate = 10
drop_rate = 10
boss_drop_rate = 10
quest_rate = 5
fishing_rate = 10
travel_rate = 10
max_players = 1000

[[worlds]]
id = 1
name = "Bera"
channels = 10
flag = 0
event_message = "Bera!"
recommended_message = "Welcome to Bera!"
exp_rate = 10
meso_rate = 10
drop_rate = 10
boss_drop_rate = 10
quest_rate = 5
fishing_rate = 10
travel_rate = 10
max_players = 1000
