[package]
name = "slate-net"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.3"
anyhow = "1.0.72"
bytes = "1.4.0"
futures = "0.3.28"
log = "0.4.20"
rand = "0.8.5"
tokio = "1.31.0"
tokio-util = { version = "0.7.8", features = ["full"] }
